# 张量的基本操作

## 张量和numpy

In [16]:
import torch
import numpy as np


# 场景1：张量->numpy
def dm01():
    t1 = torch.tensor([1, 2, 3, 4, 5])
    print(f't1: {t1},type:{type(t1)}')

    # 共享内存
    # n1 = t1.numpy()

    # 不共享内存
    n1 = t1.numpy().copy()

    print(f'n1: {n1},type:{type(n1)}')
    print('-' * 30)

    n1[0] = 100
    print(f'n1:{n1}')
    print(f't1:{t1}')


# 场景2： numpy->张量
def dm02():
    n1 =np.array([11, 22, 33])
    print(f'n1:{n1}, type:{type(n1)}')
    
    # 共享内存
    t1 = torch.from_numpy(n1)
    print(f't1:{t1}, type:{type(t1)}')
    
    t2 = torch.tensor(n1)
    print(f't2:{t2}, type:{type(t2)}')
    
    n1[0] = 100
    print(f'n1:{n1}')
    print(f't1:{t1}')
    print(f't2:{t2}')
    

# 场景3：标量张量提取元素
def dm03():
    t1 = torch.tensor([100,])
    print(f't1:{t1}, type:{type(t1)}')
    
    a = t1.item()
    print(f'a:{a}, type:{type(a)}')
    
    
if __name__ == '__main__':
    # dm01()
    dm02()
    dm03()

n1:[11 22 33], type:<class 'numpy.ndarray'>
t1:tensor([11, 22, 33], dtype=torch.int32), type:<class 'torch.Tensor'>
t2:tensor([11, 22, 33], dtype=torch.int32), type:<class 'torch.Tensor'>
n1:[100  22  33]
t1:tensor([100,  22,  33], dtype=torch.int32)
t2:tensor([11, 22, 33], dtype=torch.int32)
t1:tensor([100]), type:<class 'torch.Tensor'>
a:100, type:<class 'int'>


## 张量基本运算

In [17]:
# 张量和数值运算，有广播机制
t1 = torch.tensor([1,2,3])
t2 = torch.tensor(10)
t3 = t1 + t2
print(f't1:{t1}')
print(f't3:{t3}')
t1 += 10
print(f't1:{t1}')

# 其余-、 *、 /、//、效果同上

t1:tensor([1, 2, 3])
t3:tensor([11, 12, 13])
t1:tensor([11, 12, 13])


## 张量矩阵运算

In [18]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
print(f't1:{t1}')
t2 = torch.tensor([[1,2,3],[4,5,6]])
print(f't2:{t2}')
print('-'*30)

# 点乘：对应位置相乘
t3 = t1 * t2
print(f't3:{t3}')
print('-'*30)

# 矩阵乘法
t4 = torch.tensor([[1,2],[3,4],[5,6]])
t5 = t1 @ t4
print(f't5:{t5}')

t1:tensor([[1, 2, 3],
        [4, 5, 6]])
t2:tensor([[1, 2, 3],
        [4, 5, 6]])
------------------------------
t3:tensor([[ 1,  4,  9],
        [16, 25, 36]])
------------------------------
t5:tensor([[22, 28],
        [49, 64]])


## 张量常用运算函数 （dim参数，0表示按列，1表示按行）

In [19]:
t1 = torch.tensor([
    [1,2,3],
    [4,5,6]
],dtype = torch.float)
print(f't1:{t1}')
print('-' * 30)

print(t1.sum(dim=0))
print(t1.sum(dim=1))
print(t1.sum())
print('-'*30)
# 同理有max()、min()、mean()均有dim参数，其中mean()必须要float类型

print(t1.sqrt())
# 同理有exp()、log()、log2()、log10()、**、没有dim参数

t1:tensor([[1., 2., 3.],
        [4., 5., 6.]])
------------------------------
tensor([5., 7., 9.])
tensor([ 6., 15.])
tensor(21.)
------------------------------
tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


## 张量的索引操作

In [20]:
torch.manual_seed(24)
t1 = torch.randint(1, 10, (5, 5))
print(f't1:{t1}')

t1:tensor([[6, 9, 9, 2, 8],
        [7, 8, 5, 8, 4],
        [7, 4, 3, 9, 3],
        [6, 1, 4, 2, 8],
        [1, 2, 5, 7, 4]])


### 简单行列索引

In [21]:
print(t1[1]) # 获取第2行数据
print(t1[1, :]) # 效果同上，冒号代表所有列
print(t1[:, 2]) # 获取第3列数据

tensor([7, 8, 5, 8, 4])
tensor([7, 8, 5, 8, 4])
tensor([9, 5, 3, 4, 5])


### 列表索引（前面表示所有行，后面表示所有列）

In [22]:
print(t1[[0, 1], [1, 2]]) # 返回(0,1),(1,2)两个位置的元素
print(t1[[1, 3], [2, 4]]) # 返回(1,2),(3,4)的元素
print('-' * 30)

print(t1[[[0], [1]], [1, 2]]) # 返回0,1行,1,2列共四个元素

tensor([9, 5])
tensor([5, 8])
------------------------------
tensor([[9, 9],
        [8, 5]])


### 范围索引

In [23]:
print(t1[:3, :2]) # 前三行，前两列
print(t1[1:, :2]) # 第二行到最后一行，前两列
print(t1[1::2, ::2]) # 奇数行，偶数列，第二个冒号后代表步长

tensor([[6, 9],
        [7, 8],
        [7, 4]])
tensor([[7, 8],
        [7, 4],
        [6, 1],
        [1, 2]])
tensor([[7, 5, 4],
        [6, 4, 8]])


### 布尔索引

In [24]:
print(t1[t1[:, 2] > 5, :]) # 第3列，大于5的行的数据

tensor([[6, 9, 9, 2, 8]])


### 多维索引

In [25]:
t2 = torch.randint(1, 10, (2, 3, 4))
print(f't2:{t2}')
print('-' * 30)

print(t2[0, :, :])
print('-' * 30)

print(t2[:, 0, :])
print('-' * 30)

print(t2[:, :, 0])

t2:tensor([[[3, 4, 6, 5],
         [8, 8, 8, 3],
         [4, 9, 6, 7]],

        [[2, 8, 8, 5],
         [6, 4, 2, 2],
         [2, 7, 9, 4]]])
------------------------------
tensor([[3, 4, 6, 5],
        [8, 8, 8, 3],
        [4, 9, 6, 7]])
------------------------------
tensor([[3, 4, 6, 5],
        [2, 8, 8, 5]])
------------------------------
tensor([[3, 8, 4],
        [2, 6, 2]])


# 张量的形状操作

### reshape() 不改变张量内容前提下，改变其形状

In [26]:
t1 = torch.randint(1, 10, (2, 3))
print(f't1:{t1}, shape:{t1.shape}, row:{t1.shape[0]}, col:{t1.shape[1]}')

t2 = t1.reshape(3, 2)
print(f't2:{t2}, row:{t2.shape[0]}, col:{t2.shape[1]}')
print('-' * 30)

t3 = t1.reshape(1, 6)
print(f't3:{t3}, row:{t3.shape[0]}, col:{t3.shape[1]}')

t1:tensor([[2, 6, 3],
        [2, 3, 7]]), shape:torch.Size([2, 3]), row:2, col:3
t2:tensor([[2, 6],
        [3, 2],
        [3, 7]]), row:3, col:2
------------------------------
t3:tensor([[2, 6, 3, 2, 3, 7]]), row:1, col:6


### squeeze() 删除所有为1的维度（降维）

### unsqueeze() 在指定轴上增加一个1维度

In [27]:
t2 = t1.unsqueeze(0)
print(f't2:{t2}, shape:{t2.shape}')
print('-' * 30)

t3 = t1.unsqueeze(1)
print(f't3:{t3}, shape:{t3.shape}')
print('-' * 30)

t4 = torch.randint(1, 10,(2, 1, 3, 1, 1))
print(f't4:{t4}, shape:{t4.shape}')
print('-' * 30)
t5 = t4.squeeze()
print(f't5:{t5}, shape:{t5.shape}')


t2:tensor([[[2, 6, 3],
         [2, 3, 7]]]), shape:torch.Size([1, 2, 3])
------------------------------
t3:tensor([[[2, 6, 3]],

        [[2, 3, 7]]]), shape:torch.Size([2, 1, 3])
------------------------------
t4:tensor([[[[[5]],

          [[1]],

          [[7]]]],



        [[[[9]],

          [[2]],

          [[3]]]]]), shape:torch.Size([2, 1, 3, 1, 1])
------------------------------
t5:tensor([[5, 1, 7],
        [9, 2, 3]]), shape:torch.Size([2, 3])


### tanspose() 一次交换2个维度

### permute() 一次交换多个维度

In [28]:
t1 = torch.randint(1, 10, (2, 3, 4))
print(f't1:{t1}, shape:{t1.shape}')
print('-' * 30)

# 改变维度(2,3,4)->(3,2,4)
t2 = t1.transpose(0, 1)
print(f't2:{t2}, shape:{t2.shape}')
print(f't1:{t1}, shape:{t1.shape}')
print('-' * 30)

# 改变维度(2,3,4)->(4,2,3)
t3 = t1.permute(2, 0, 1)
print(f't3:{t3}, shape:{t3.shape}')

t1:tensor([[[1, 9, 6, 8],
         [5, 7, 5, 8],
         [5, 9, 5, 6]],

        [[2, 1, 3, 9],
         [8, 7, 1, 6],
         [5, 3, 8, 3]]]), shape:torch.Size([2, 3, 4])
------------------------------
t2:tensor([[[1, 9, 6, 8],
         [2, 1, 3, 9]],

        [[5, 7, 5, 8],
         [8, 7, 1, 6]],

        [[5, 9, 5, 6],
         [5, 3, 8, 3]]]), shape:torch.Size([3, 2, 4])
t1:tensor([[[1, 9, 6, 8],
         [5, 7, 5, 8],
         [5, 9, 5, 6]],

        [[2, 1, 3, 9],
         [8, 7, 1, 6],
         [5, 3, 8, 3]]]), shape:torch.Size([2, 3, 4])
------------------------------
t3:tensor([[[1, 5, 5],
         [2, 8, 5]],

        [[9, 7, 9],
         [1, 7, 3]],

        [[6, 5, 5],
         [3, 1, 8]],

        [[8, 8, 6],
         [9, 6, 3]]]), shape:torch.Size([4, 2, 3])


### 连续张量：内存中的存储顺序与张量中的显示顺序相同
### view() 只能修改连续的张量的形状
### contiguous() 把不连续的张量变成连续的张量，即：基于张量中显示的顺序，修改内存中的存储顺序
### is_contiguous() 判断张量是否连续

In [29]:
t1 = torch.randint(1, 10, (2, 3))
print(f't1:{t1}, shape:{t1.shape}')
print(t1.is_contiguous())

t2 = t1.view(3, 2)
print(f't2:{t2}, shape:{t2.shape}')
print(t2.is_contiguous())
print('-' * 30)

t3 = t1.transpose(0, 1)
print(f't3:{t3}, shape:{t3.shape}')
print(t3.is_contiguous())
print('-' * 30)

t4 = t3.contiguous().view(2, 3)
print(f't4:{t4}, shape:{t4.shape}')
print(t4.is_contiguous())

t1:tensor([[8, 8, 1],
        [8, 9, 4]]), shape:torch.Size([2, 3])
True
t2:tensor([[8, 8],
        [1, 8],
        [9, 4]]), shape:torch.Size([3, 2])
True
------------------------------
t3:tensor([[8, 8],
        [8, 9],
        [1, 4]]), shape:torch.Size([3, 2])
False
------------------------------
t4:tensor([[8, 8, 8],
        [9, 1, 4]]), shape:torch.Size([2, 3])
True


### 张量的拼接
### cat()多个张量根据指定维度拼接，不改变维度数，除了拼接的维度外，其它维度必须一致

### stack()在一个新的维度上连接一系列张量，增加一个维度，所有维度都要一致

In [30]:
t1 = torch.randint(1, 10, (2, 3))
print(f't1:{t1}, shape:{t1.shape}')
t2 = torch.randint(1, 10, (2, 3))
print(f't2:{t2}, shape:{t2.shape}')
t3 = torch.cat((t1, t2), dim=0)     # (2,3)+(2,3) = (4,3)
print(f't3:{t3}, shape:{t3.shape}')
t4 = torch.cat((t1, t2), dim=1)     # (2,3)+(2,3) = (2,6)
print(f't4:{t4}, shape:{t4.shape}')
print('-' * 30)

t5 = torch.stack([t1, t2], dim=0)
print(f't5:{t5}, shape:{t5.shape}')
t6 = torch.stack([t1, t2], dim=2)
print(f't6:{t6}, shape:{t6.shape}')
# 原大小(2,3)，2个张量
# 拼接哪个维度，就把2放到( 2,  3  )的哪个位置

t1:tensor([[3, 8, 6],
        [1, 4, 6]]), shape:torch.Size([2, 3])
t2:tensor([[7, 7, 6],
        [6, 1, 3]]), shape:torch.Size([2, 3])
t3:tensor([[3, 8, 6],
        [1, 4, 6],
        [7, 7, 6],
        [6, 1, 3]]), shape:torch.Size([4, 3])
t4:tensor([[3, 8, 6, 7, 7, 6],
        [1, 4, 6, 6, 1, 3]]), shape:torch.Size([2, 6])
------------------------------
t5:tensor([[[3, 8, 6],
         [1, 4, 6]],

        [[7, 7, 6],
         [6, 1, 3]]]), shape:torch.Size([2, 2, 3])
t6:tensor([[[3, 7],
         [8, 7],
         [6, 6]],

        [[1, 6],
         [4, 1],
         [6, 3]]]), shape:torch.Size([2, 3, 2])
